services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - '/etc/letsencrypt:/etc/letsencrypt'
    # depends_on:
    #   - molecules_frontend
      # - molecules_backend
    networks:
      - app_network

  molecules_frontend:
    build:
      context: ./molecules--web
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./molecules--web/src:/usr/src/app/src
    networks:
      - app_network

  molecules_backend:
    build:
      context: ./molecules--server
      dockerfile: Dockerfile
    command: gunicorn api_NFTMolecules.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      - ./molecules--server:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16