services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - '/etc/letsencrypt:/etc/letsencrypt'
      - '/etc/ssl/chemx.io:/etc/ssl'
    # depends_on:
    #   - molecules_frontend
      # - molecules_backend
    networks:
      - app_network

  molecules_frontend:
    build:
      context: ./molecules--web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./molecules--web/src:/usr/src/app/src
    networks:
      - app_network

  molecules_backend:
    build:
      context: ./molecules--server
      dockerfile: Dockerfile
    command: gunicorn api_NFTMolecules.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./molecules--server:/app
      - ./data_media:/app/molecules/media
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16